### PR TITLE
Verge Blockchain Download Script for OS X users

### PR DESCRIPTION
**Pull request by burakim**
- Modified version of readme file
- verge_blockchain_download script for os x wallet

### CODE REVIEW

**Comment by burakim** [comment]
@justinvforvendetta Did you have a chance to look at the script?

**Comment by justinvforvendetta** [comment]
yeah it looks solid @burakim you should also put your xvg address and info in the README

**Comment by burakim** [comment]
@justinvforvendetta how can I text you? I tried Discord, Twitter; however, I haven't got any response from you. I would like to contribute VERGE project more.

**Comment by justinvforvendetta** [comment]
discord, you can pm me directly, vergedev

**Pull request merged**
